name: Validate Structurizr DSL

on:
  push:
    paths:
      - "**.dsl"
  pull_request:
    paths:
      - "**.dsl"
jobs:
  validate-dsl:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check Docker availability
        id: docker-check
        run: |
          if command -v docker &> /dev/null; then
            echo "docker=true" >> $GITHUB_OUTPUT
          else
            echo "docker=false" >> $GITHUB_OUTPUT
          fi
      # Find and validate all DSL files
      - name: Validate Structurizr DSL files
        run: |
          for file in *.dsl; do
            echo "Validating $file"
            docker run --rm -v "$(pwd):/workspace" structurizr/cli validate -workspace /workspace/"$file"
          done