name: Check Docker + Structurizr CLI

on:
  push:
    branches: [ "main" ]   # you can change this to any branch
  pull_request:

jobs:
  check-docker-structurizr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker availability
        run: |
          if command -v docker &> /dev/null; then
            echo "✅ Docker is installed"
            docker --version
          else
            echo "❌ Docker is NOT installed"
            exit 1
          fi

      - name: Test Structurizr CLI image
        run: |
          echo "Pulling Structurizr CLI image..."
          docker pull structurizr/cli:latest
          
          echo "Running Structurizr CLI version command..."
          docker run --rm structurizr/cli:latest version
      - name: Validate all projects
        run: |
          echo "🔎 Validating all .dsl files in repository..."
          for project in systemA; do
            echo "Validating $project at $GITHUB_WORKSPACE..."
            project_path="$GITHUB_WORKSPACE/$project"
            echo "Project path is $project_path"
            if [ ! -d "$project_path" ]; then
              echo "❌ Project directory $project_path does not exist."
              exit 1
            fi
            if [ ! -f "$project_path/workspace.dsl" ]; then
              echo "❌ workspace.dsl file does not exist in $project_path."
              exit 1
            fi
            echo "Validating $project_path/workspace.dsl..."
            # Run Structurizr CLI validate command
            # using the mounted workspace directory
            echo "Running Structurizr CLI validate command..."
            # Ensure the workspace.dsl file exists
            if [ ! -f "$project_path/workspace.dsl" ]; then
              echo "❌ workspace.dsl file does not exist in $project_path."
              exit 1
            fi
            # Run the validation command
            echo "Running Structurizr CLI validate command on $project_path/workspace.dsl..."
            docker run --rm -v "$project_path":/workspace structurizr/cli:latest validate -workspace /workspace/workspace.dsl
          done