name: Validate Structurizr DSL

on:
  push:
    paths:
      - '**/*.dsl'

jobs:
  validate-dsl:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check Docker version
        run: |
          docker --version
          docker info
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Structurizr DSL
        run: structurizr validate -workspace /workspace/**/*.dsl