name: Validate Structurizr DSL

on:
  push:
    paths:
      - "**.dsl"
  pull_request:
    paths:
      - "**.dsl"
      workflow_dispatch:
        inputs:
          check_docker:
            description: "Check if Docker is installed and print version"
            required: false
            default: "false"
jobs:
  validate-dsl:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Find and validate all DSL files
      - name: Validate Structurizr DSL files
        run: |
          for file in *.dsl; do
            echo "Validating $file"
            docker run --rm -v "$(pwd):/workspace" structurizr/cli validate -workspace /workspace/"$file"
          done