name: Check Docker + Structurizr CLI

on:
  push:
    branches: [ "main" ]   # you can change this to any branch
  pull_request:

jobs:
  check-docker-structurizr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker availability
        run: |
          if command -v docker &> /dev/null; then
            echo "✅ Docker is installed"
            docker --version
          else
            echo "❌ Docker is NOT installed"
            exit 1
          fi

      - name: Test Structurizr CLI image
        run: |
          echo "Pulling Structurizr CLI image..."
          docker pull structurizr/cli:latest
          
          echo "Running Structurizr CLI version command..."
          docker run --rm structurizr/cli:latest version
      - name: Validate all projects
        run: |
          echo "🔎 Validating all .dsl files in repository..."
          for project in systemA; do
            echo "Validating $project at $GITHUB_WORKSPACE..."
            project_path="$GITHUB_WORKSPACE/$project"
            docker run --rm -v "$project_path":/workspace structurizr/cli:latest validate -workspace /workspace/workspace.dsl
          done